@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Auth

### Login
# @name login
POST http://{{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "uid": "root",
  "password": "abcd1234"
}

###

@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

### Logout
POST http://{{host}}/api/auth/logout
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Refresh Token
POST http://{{host}}/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

### Get Profile
GET http://{{host}}/api/auth/profile
Authorization: Bearer {{accessToken}}

###

### Me

### Get Me
GET http://{{host}}/api/me
Authorization: Bearer {{accessToken}}

###

### Change Name
PATCH http://{{host}}/api/me/change-name
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "用戶一號"
}

###

### Change Password
PATCH http://{{host}}/api/me/change-password
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "newPassword": "666666",
  "confirmPassword": "666666"
}

###

### Transactions

### Get Transactions
GET http://{{host}}/api/transactions
    ?page=1
    &pageSize=10
    &sort=createdAt:asc
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Get One Transaction
GET http://{{host}}/api/transactions/TRX-20250421-000311-01894
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Create Transaction
POST http://{{host}}/api/transactions
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "remark":"不吃早餐",
  "items": [
    {
      "uid":"root",
      "value":-100,
      "details":"早餐代墊"
    },
    {
      "uid":"ts-01",
      "value":100,
      "details":"早餐"
    }
  ]
}

###

### Users

### Get Users
GET http://{{host}}/api/users
  ?showDisable=false
  &fields=department
  &fields=role
  &sort=balance:desc
  &sort=id:asc
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Get One User
GET http://{{host}}/api/users/ts-003
  ?fields=isInit,
  &fields=role,
  &fields=version
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Create User
POST http://{{host}}/api/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "uid":"ts-02",
  "name":"test02",
  "roleId":1,
  "departmentId":1
}

###

### Edit User
PUT http://{{host}}/api/users/ts-003
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "roleId": 1,
  "version": 6
}

###

### Disable User
PATCH http://{{host}}/api/users/ts-002/disable
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Enable User
PATCH http://{{host}}/api/users/ts-002/enable
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Reset User Password
PATCH http://{{host}}/api/users/ts-002/reset-password
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}
###

### Get User Transaction Items
GET http://{{host}}/api/users/ts-001/transaction-items
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Get User Balance Logs
GET http://{{host}}/api/users/ts-001/balance-logs
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Get Overview

GET http://{{host}}/api/overview
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Get Roles

GET http://{{host}}/api/roles
  ?includePermissions=true
Content-Type: {{contentType}}  
Authorization: Bearer {{accessToken}}

###

### Get Departments

GET http://{{host}}/api/departments
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Notifications (Admin)

### Get Notifications
GET http://{{host}}/api/notifications
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Create Notification
POST http://{{host}}/api/notifications
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "title": "Test Notification",
  "content": "This is a test notification",
  "targets": ["ts-01", "ts-02"]
}

###

### Delete Notification
DELETE http://{{host}}/api/notifications/1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### User Notifications

### Get User Notifications
GET http://{{host}}/api/user-notifications
  ?status=all
  &limit=3
  &cursor=5
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Get User Unread Notification Count
GET http://{{host}}/api/user-notifications/unread-count
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Mark All User Notifications as Read
PATCH http://{{host}}/api/user-notifications/mark-all-read
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###

### Mark User Notification as Read
PATCH http://{{host}}/api/user-notifications/1/mark-read
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}
